{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"decoder","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup"]]},"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup\/init(from:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Initializer","modules":[{"name":"FireblocksSDK"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"externalID":"s:13FireblocksSDK9KeyBackupC4fromACs7Decoder_p_tKcfc","title":"init(from:)"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"code":"Decodable.init(from:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/fireblockssdk\/keybackup\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyBackup":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyBackup","kind":"identifier"}],"url":"\/documentation\/fireblockssdk\/keybackup","abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyBackupStatus for each key"}],"navigatorTitle":[{"text":"KeyBackup","kind":"identifier"}],"title":"KeyBackup"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyBackup/init(from:)":{"title":"init(from:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/fireblockssdk\/keybackup\/init(from:)","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/title","value":"KeyBackup"},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/fragments","value":[{"text":"KeyBackup","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/navigatorTitle","value":[{"text":"KeyBackup","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}