{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyBackup","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(pl)NSObject","doc:\/\/com.fireblocks.Fireblocks\/s7CVarArgP","doc:\/\/com.fireblocks.Fireblocks\/s28CustomDebugStringConvertibleP","doc:\/\/com.fireblocks.Fireblocks\/s23CustomStringConvertibleP","doc:\/\/com.fireblocks.Fireblocks\/Se","doc:\/\/com.fireblocks.Fireblocks\/SE","doc:\/\/com.fireblocks.Fireblocks\/SQ","doc:\/\/com.fireblocks.Fireblocks\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Class","modules":[{"name":"FireblocksSDK"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyBackup","kind":"identifier"}],"externalID":"c:@M@FireblocksSDK@objc(cs)KeyBackup","navigatorTitle":[{"kind":"identifier","text":"KeyBackup"}],"title":"KeyBackup"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyBackupStatus for each key"}],"topicSections":[{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup\/init(from:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup\/keyBackupStatus","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup\/keyId"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup\/description()"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/keybackup"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fireblockssdk\/keybackup"]}],"references":{"doc://com.fireblocks.Fireblocks/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/Se"},"doc://com.fireblocks.Fireblocks/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s23CustomStringConvertibleP"},"doc://com.fireblocks.Fireblocks/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SH"},"doc://com.fireblocks.Fireblocks/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s28CustomDebugStringConvertibleP"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyBackup/keyId":{"kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup\/keyId","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/fireblockssdk\/keybackup\/keyid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"keyId"},"doc://com.fireblocks.Fireblocks/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SE"},"doc://com.fireblocks.Fireblocks/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SQ"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyBackup":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyBackup","kind":"identifier"}],"url":"\/documentation\/fireblockssdk\/keybackup","abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyBackupStatus for each key"}],"navigatorTitle":[{"text":"KeyBackup","kind":"identifier"}],"title":"KeyBackup"},"doc://com.fireblocks.Fireblocks/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/objc(pl)NSObject"},"doc://com.fireblocks.Fireblocks/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s7CVarArgP"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyBackup/init(from:)":{"title":"init(from:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/fireblockssdk\/keybackup\/init(from:)","abstract":[],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyBackup/description()":{"title":"description()","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup\/description()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/fireblockssdk\/keybackup\/description()","abstract":[],"type":"topic"},"doc://com.fireblocks.Fireblocks/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyBackup/keyBackupStatus":{"title":"keyBackupStatus","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup\/keyBackupStatus","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyBackupStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"KeyBackupStatus","kind":"typeIdentifier","preciseIdentifier":"s:13FireblocksSDK15KeyBackupStatusO"}],"url":"\/documentation\/fireblockssdk\/keybackup\/keybackupstatus","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"KeyBackup"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"KeyBackup","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"KeyBackup","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"],"title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyBackup"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/title","value":"KeyBackup"},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/fragments","value":[{"text":"KeyBackup","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/navigatorTitle","value":[{"text":"KeyBackup","kind":"identifier"}]}]}]}