{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"approveJoinWalletRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"requestId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)JoinWalletDescriptor","text":"JoinWalletDescriptor","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"requestId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The request id to approve"}]}]}]},{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked with the Set of "},{"type":"reference","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor","isActive":true},{"type":"text","text":" with the information of all provisioned keys in the wallet"}]}],"kind":"content"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/approveJoinWalletRequest(requestId:)"},"abstract":[{"type":"text","text":"Approve a join wallet request"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/AddDeviceProtocol-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/fireblocks\/approvejoinwalletrequest(requestid:)"]}],"metadata":{"externalID":"s:13FireblocksSDK0A0C24approveJoinWalletRequest9requestIdShyAA0dE10DescriptorCGSS_tYaKF","title":"approveJoinWalletRequest(requestId:)","roleHeading":"Instance Method","extendedModule":"FireblocksSDK","modules":[{"name":"FireblocksSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"approveJoinWalletRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)JoinWalletDescriptor","kind":"typeIdentifier","text":"JoinWalletDescriptor"},{"kind":"text","text":">"}],"role":"symbol","symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/AddDeviceProtocol-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/AddDeviceProtocol-Implementations","url":"\/documentation\/fireblockssdk\/fireblocks\/adddeviceprotocol-implementations","abstract":[],"title":"AddDeviceProtocol Implementations"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor":{"kind":"symbol","title":"JoinWalletDescriptor","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinWalletDescriptor"}],"url":"\/documentation\/fireblockssdk\/joinwalletdescriptor","abstract":[{"text":"Information about the approval request to join an existing wallet or the join request to an existing wallet.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"JoinWalletDescriptor"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/approveJoinWalletRequest(requestId:)":{"type":"topic","abstract":[{"type":"text","text":"Approve a join wallet request"}],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/approveJoinWalletRequest(requestId:)","title":"approveJoinWalletRequest(requestId:)","kind":"symbol","url":"\/documentation\/fireblockssdk\/fireblocks\/approvejoinwalletrequest(requestid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"approveJoinWalletRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)JoinWalletDescriptor","kind":"typeIdentifier","text":"JoinWalletDescriptor"},{"kind":"text","text":">"}],"role":"symbol"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks":{"kind":"symbol","title":"Fireblocks","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fireblocks"}],"url":"\/documentation\/fireblockssdk\/fireblocks","abstract":[{"text":"The Fireblocks SDK main class. Use it to perform all of the SDK functionality.","type":"text"},{"text":" ","type":"text"},{"text":"Call Fireblocks.initialize to initialize the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Fireblocks"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"JoinWalletDescriptor","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/title"},{"op":"replace","value":[{"text":"JoinWalletDescriptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/fragments"},{"op":"replace","value":[{"text":"JoinWalletDescriptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/navigatorTitle"}]}]}