{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backupKeys"},{"kind":"text","text":"("},{"kind":"externalParam","text":"passphrase"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"passphraseId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyBackup","kind":"typeIdentifier","text":"KeyBackup"},{"kind":"text","text":">"}]}],"kind":"declarations"},{"parameters":[{"name":"passphrase","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Passphrase In order to encrypt and backup the MPC key."},{"type":"text","text":" "},{"type":"text","text":"The passPhrase must be unique and secure. Use generateRandomPassphrase method"}]}]}],"kind":"parameters"},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Set of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup"},{"type":"text","text":" with the information of all backed up keys."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/BackupProtocol-Implementations"]]},"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/backupKeys(passphrase:passphraseId:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"FireblocksSDK"}],"extendedModule":"FireblocksSDK","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backupKeys","kind":"identifier"},{"text":"(","kind":"text"},{"text":"passphrase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"passphraseId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"KeyBackup","kind":"typeIdentifier","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyBackup"},{"text":">","kind":"text"}],"externalID":"s:13FireblocksSDK0A0C10backupKeys10passphrase0E2IdShyAA9KeyBackupCGSS_SStYaKF","title":"backupKeys(passphrase:passphraseId:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Backup end-user keys to Fireblocks","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/fireblocks\/backupkeys(passphrase:passphraseid:)"]}],"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/BackupProtocol-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/BackupProtocol-Implementations","url":"\/documentation\/fireblockssdk\/fireblocks\/backupprotocol-implementations","abstract":[],"title":"BackupProtocol Implementations"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/backupKeys(passphrase:passphraseId:)":{"title":"backupKeys(passphrase:passphraseId:)","abstract":[{"type":"text","text":"Backup end-user keys to Fireblocks"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/fireblocks\/backupkeys(passphrase:passphraseid:)","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/backupKeys(passphrase:passphraseId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backupKeys","kind":"identifier"},{"text":"(","kind":"text"},{"text":"passphrase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"passphraseId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyBackup","text":"KeyBackup"},{"kind":"text","text":">"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks":{"kind":"symbol","title":"Fireblocks","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fireblocks"}],"url":"\/documentation\/fireblockssdk\/fireblocks","abstract":[{"text":"The Fireblocks SDK main class. Use it to perform all of the SDK functionality.","type":"text"},{"text":" ","type":"text"},{"text":"Call Fireblocks.initialize to initialize the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Fireblocks"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyBackup":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyBackup","kind":"identifier"}],"url":"\/documentation\/fireblockssdk\/keybackup","abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyBackupStatus for each key"}],"navigatorTitle":[{"text":"KeyBackup","kind":"identifier"}],"title":"KeyBackup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/title","op":"replace","value":"KeyBackup"},{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/fragments","op":"replace","value":[{"kind":"identifier","text":"KeyBackup"}]},{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"KeyBackup"}]}]}]}