{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateMPCKeys"},{"kind":"text","text":"("},{"kind":"externalParam","text":"algorithms"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Algorithm","kind":"typeIdentifier","preciseIdentifier":"s:13FireblocksSDK9AlgorithmO","text":"Algorithm"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor","kind":"typeIdentifier","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyDescriptor","text":"KeyDescriptor"},{"kind":"text","text":">) -> ()) "},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"algorithms","content":[{"inlineContent":[{"type":"text","text":"A Set of supported "},{"type":"reference","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Algorithm","isActive":true}],"type":"paragraph"}]},{"name":"callback","content":[{"inlineContent":[{"type":"text","text":"Invoked with the Set of "},{"type":"reference","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor","isActive":true},{"type":"text","text":" with the information of all keys"}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/OnboardingProtocol-Implementations"]]},"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/generateMPCKeys(algorithms:callback:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"FireblocksSDK"}],"extendedModule":"FireblocksSDK","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateMPCKeys"},{"kind":"text","text":"("},{"kind":"externalParam","text":"algorithms"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:13FireblocksSDK9AlgorithmO","text":"Algorithm"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyDescriptor","text":"KeyDescriptor"},{"kind":"text","text":">) -> ()) "},{"kind":"keyword","text":"throws"}],"externalID":"s:13FireblocksSDK0A0C15generateMPCKeys10algorithms8callbackyShyAA9AlgorithmOG_yShyAA13KeyDescriptorCGctKF","title":"generateMPCKeys(algorithms:callback:)"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Start the MPC setup process for selected algorithms. Throws illegal exceptions."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/fireblocks\/generatempckeys(algorithms:callback:)"]}],"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/generateMPCKeys(algorithms:callback:)":{"title":"generateMPCKeys(algorithms:callback:)","abstract":[{"type":"text","text":"Start the MPC setup process for selected algorithms. Throws illegal exceptions."}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/fireblocks\/generatempckeys(algorithms:callback:)","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/generateMPCKeys(algorithms:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"generateMPCKeys","kind":"identifier"},{"text":"(","kind":"text"},{"text":"algorithms","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:13FireblocksSDK9AlgorithmO","text":"Algorithm","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"callback","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyDescriptor","text":"KeyDescriptor"},{"kind":"text","text":">) -> ()) "},{"kind":"keyword","text":"throws"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyStatus for each key"}],"kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor","url":"\/documentation\/fireblockssdk\/keydescriptor","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"KeyDescriptor","kind":"identifier"}],"title":"KeyDescriptor","navigatorTitle":[{"text":"KeyDescriptor","kind":"identifier"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/OnboardingProtocol-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/OnboardingProtocol-Implementations","url":"\/documentation\/fireblockssdk\/fireblocks\/onboardingprotocol-implementations","abstract":[],"title":"OnboardingProtocol Implementations"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks":{"kind":"symbol","title":"Fireblocks","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fireblocks"}],"url":"\/documentation\/fireblockssdk\/fireblocks","abstract":[{"text":"The Fireblocks SDK main class. Use it to perform all of the SDK functionality.","type":"text"},{"text":" ","type":"text"},{"text":"Call Fireblocks.initialize to initialize the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Fireblocks"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Algorithm":{"navigatorTitle":[{"text":"Algorithm","kind":"identifier"}],"title":"Algorithm","abstract":[{"text":"Supported Signature algorithms for MPC keys","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/algorithm","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Algorithm","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Algorithm"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/title","op":"replace","value":"KeyDescriptor"},{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/fragments","op":"replace","value":[{"kind":"identifier","text":"KeyDescriptor"}]},{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"KeyDescriptor"}]}]}]}