{"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/TakeoverProtocol-Implementations"]]},"metadata":{"extendedModule":"FireblocksSDK","roleHeading":"Instance Method","title":"takeover()","externalID":"s:13FireblocksSDK0A0C8takeoverShyAA7FullKeyCGyYaKF","symbolKind":"method","modules":[{"name":"FireblocksSDK"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"takeover","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"FullKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)FullKey"},{"text":">","kind":"text"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"takeover","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)FullKey","text":"FullKey","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Set of "},{"type":"reference","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey","isActive":true},{"type":"text","text":" that contains extended private key as xprv \/ fprv and an extended public key as xpub \/ fpub or a "},{"type":"reference","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksError","isActive":true}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Reconstructs all shares of a MPC key (mobile + cloud shares) into the full public and private keys"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/fireblocks\/takeover()"]}],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/takeover()","interfaceLanguage":"swift"},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/takeover()":{"title":"takeover()","abstract":[{"type":"text","text":"Reconstructs all shares of a MPC key (mobile + cloud shares) into the full public and private keys"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/fireblocks\/takeover()","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/takeover()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"takeover"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)FullKey","text":"FullKey"},{"kind":"text","text":">"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/TakeoverProtocol-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/TakeoverProtocol-Implementations","url":"\/documentation\/fireblockssdk\/fireblocks\/takeoverprotocol-implementations","abstract":[],"title":"TakeoverProtocol Implementations"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks":{"kind":"symbol","title":"Fireblocks","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fireblocks"}],"url":"\/documentation\/fireblockssdk\/fireblocks","abstract":[{"text":"The Fireblocks SDK main class. Use it to perform all of the SDK functionality.","type":"text"},{"text":" ","type":"text"},{"text":"Call Fireblocks.initialize to initialize the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Fireblocks"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FullKey":{"navigatorTitle":[{"kind":"identifier","text":"FullKey"}],"title":"FullKey","abstract":[{"type":"text","text":"Information about the FullKey generated"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/fullkey","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullKey"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksError":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FireblocksError"}],"url":"\/documentation\/fireblockssdk\/fireblockserror","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FireblocksError"}],"title":"FireblocksError"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/title","value":"FullKey"},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/fragments","value":[{"text":"FullKey","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/navigatorTitle","value":[{"text":"FullKey","kind":"identifier"}]}]}]}