{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"algorithm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Algorithm","preciseIdentifier":"s:13FireblocksSDK9AlgorithmO","text":"Algorithm"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/algorithm"},"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"FireblocksSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"algorithm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Algorithm","kind":"typeIdentifier","preciseIdentifier":"s:13FireblocksSDK9AlgorithmO"},{"text":"?","kind":"text"}],"externalID":"s:13FireblocksSDK13KeyDescriptorC9algorithmAA9AlgorithmOSgvp","title":"algorithm"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/keydescriptor\/algorithm"]}],"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Algorithm":{"navigatorTitle":[{"text":"Algorithm","kind":"identifier"}],"title":"Algorithm","abstract":[{"text":"Supported Signature algorithms for MPC keys","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/algorithm","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Algorithm","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Algorithm"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyStatus for each key"}],"kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor","url":"\/documentation\/fireblockssdk\/keydescriptor","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"KeyDescriptor","kind":"identifier"}],"title":"KeyDescriptor","navigatorTitle":[{"text":"KeyDescriptor","kind":"identifier"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor/algorithm":{"title":"algorithm","abstract":[],"role":"symbol","url":"\/documentation\/fireblockssdk\/keydescriptor\/algorithm","kind":"symbol","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/algorithm","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"algorithm","kind":"identifier"},{"kind":"text","text":": "},{"text":"Algorithm","kind":"typeIdentifier","preciseIdentifier":"s:13FireblocksSDK9AlgorithmO"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/title","op":"replace","value":"KeyDescriptor"},{"op":"replace","value":[{"kind":"identifier","text":"KeyDescriptor"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/fragments"},{"op":"replace","value":[{"text":"KeyDescriptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}