{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/keydescriptor\/identifiable-implementations"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/Identifiable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor"]]},"kind":"article","metadata":{"title":"Identifiable Implementations","roleHeading":"API Collection","modules":[{"name":"FireblocksSDK"}],"role":"collectionGroup"},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/id"],"anchor":"Instance-Properties"}],"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor/id":{"role":"symbol","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/id","url":"\/documentation\/fireblockssdk\/keydescriptor\/id","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SO","text":"ObjectIdentifier","kind":"typeIdentifier"}],"title":"id"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyStatus for each key"}],"kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor","url":"\/documentation\/fireblockssdk\/keydescriptor","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"KeyDescriptor","kind":"identifier"}],"title":"KeyDescriptor","navigatorTitle":[{"text":"KeyDescriptor","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"KeyDescriptor","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"KeyDescriptor"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"KeyDescriptor"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/navigatorTitle"}]}]}