{"hierarchy":{"paths":[[]]},"metadata":{"title":"FireblocksSDK","symbolKind":"module","externalID":"FireblocksSDK","modules":[{"name":"FireblocksSDK"}],"roleHeading":"Framework","role":"collection"},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/ClearDevice","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/DeviceLogger","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Envs","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksOptions","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyData","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyTakeover","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/ReportingOptions","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Status","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/TransactionSignature"],"title":"Classes","anchor":"Classes","generated":true},{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/EventHandlerDelegate","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksJoinWalletHandler","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksPassphraseResolver","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyStorageDelegate","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/MessageHandlerDelegate","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/ReportingOptionsProtocol"],"title":"Protocols","anchor":"Protocols","generated":true},{"title":"Structures","anchor":"Structures","generated":true,"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Bridge","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/DerivationParams","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Env","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksError","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/LogEntry","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/ReportEventsBody","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/ReportEventsPayload"]},{"title":"Functions","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/tryBlock(_:)"],"anchor":"Functions","generated":true},{"identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Algorithm","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/BridgeType","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/DeviceStatus","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksEnvironment","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksEvent","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletStatus","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackupStatus","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecoveryStatus","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyStatus","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyTakeoverStatus","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/LogLevel","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/TransactionSignatureStatus","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Value"],"title":"Enumerations","anchor":"Enumerations","generated":true}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk"]},{"paths":["\/documentation\/fireblockssdk"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK"},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/tryBlock(_:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/tryBlock(_:)","title":"tryBlock(_:)","kind":"symbol","url":"\/documentation\/fireblockssdk\/tryblock(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tryBlock","kind":"identifier"},{"kind":"text","text":"(() -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSException","kind":"typeIdentifier","text":"NSException"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"tryBlock"}],"role":"symbol"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/ReportingOptionsProtocol":{"navigatorTitle":[{"kind":"identifier","text":"ReportingOptionsProtocol"}],"title":"ReportingOptionsProtocol","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/reportingoptionsprotocol","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/ReportingOptionsProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportingOptionsProtocol"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/LogEntry":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/LogEntry","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogEntry"}],"url":"\/documentation\/fireblockssdk\/logentry","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"LogEntry"}],"title":"LogEntry"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyStatus for each key"}],"kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor","url":"\/documentation\/fireblockssdk\/keydescriptor","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"KeyDescriptor","kind":"identifier"}],"title":"KeyDescriptor","navigatorTitle":[{"text":"KeyDescriptor","kind":"identifier"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksJoinWalletHandler":{"navigatorTitle":[{"text":"FireblocksJoinWalletHandler","kind":"identifier"}],"title":"FireblocksJoinWalletHandler","abstract":[{"text":"This interface is used to handle join wallet requests as a destination device. It is notified when a request was made to join a wallet and when a provisioner was found.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/fireblocksjoinwallethandler","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksJoinWalletHandler","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FireblocksJoinWalletHandler","kind":"identifier"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/MessageHandlerDelegate":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/MessageHandlerDelegate","title":"MessageHandlerDelegate","kind":"symbol","url":"\/documentation\/fireblockssdk\/messagehandlerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageHandlerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"MessageHandlerDelegate","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks":{"kind":"symbol","title":"Fireblocks","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fireblocks"}],"url":"\/documentation\/fireblockssdk\/fireblocks","abstract":[{"text":"The Fireblocks SDK main class. Use it to perform all of the SDK functionality.","type":"text"},{"text":" ","type":"text"},{"text":"Call Fireblocks.initialize to initialize the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Fireblocks"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyBackup":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyBackup","kind":"identifier"}],"url":"\/documentation\/fireblockssdk\/keybackup","abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyBackupStatus for each key"}],"navigatorTitle":[{"text":"KeyBackup","kind":"identifier"}],"title":"KeyBackup"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletStatus":{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletStatus","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"JoinWalletStatus","kind":"identifier"}],"abstract":[],"url":"\/documentation\/fireblockssdk\/joinwalletstatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoinWalletStatus","kind":"identifier"}],"title":"JoinWalletStatus"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Envs":{"kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Envs","role":"symbol","type":"topic","navigatorTitle":[{"text":"Envs","kind":"identifier"}],"abstract":[],"url":"\/documentation\/fireblockssdk\/envs","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Envs","kind":"identifier"}],"title":"Envs"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/ReportEventsPayload":{"navigatorTitle":[{"text":"ReportEventsPayload","kind":"identifier"}],"title":"ReportEventsPayload","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/reporteventspayload","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/ReportEventsPayload","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReportEventsPayload"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksOptions":{"navigatorTitle":[{"kind":"identifier","text":"FireblocksOptions"}],"title":"FireblocksOptions","abstract":[{"type":"text","text":"Various initialization options fore the Fireblocks SDK"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/fireblocksoptions","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FireblocksOptions"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksEnvironment":{"navigatorTitle":[{"text":"FireblocksEnvironment","kind":"identifier"}],"title":"FireblocksEnvironment","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/fireblocksenvironment","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksEnvironment","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FireblocksEnvironment","kind":"identifier"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/ReportEventsBody":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/ReportEventsBody","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportEventsBody"}],"url":"\/documentation\/fireblockssdk\/reporteventsbody","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ReportEventsBody"}],"title":"ReportEventsBody"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Value":{"navigatorTitle":[{"kind":"identifier","text":"Value"}],"title":"Value","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/value","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Value","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Value"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/EventHandlerDelegate":{"navigatorTitle":[{"kind":"identifier","text":"EventHandlerDelegate"}],"title":"EventHandlerDelegate","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/eventhandlerdelegate","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/EventHandlerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventHandlerDelegate"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/BridgeType":{"kind":"symbol","title":"BridgeType","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/BridgeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BridgeType"}],"url":"\/documentation\/fireblockssdk\/bridgetype","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"BridgeType"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksEvent":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FireblocksEvent"}],"url":"\/documentation\/fireblockssdk\/fireblocksevent","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FireblocksEvent"}],"title":"FireblocksEvent"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/LogLevel":{"navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"title":"LogLevel","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/loglevel","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery":{"navigatorTitle":[{"text":"KeyRecovery","kind":"identifier"}],"title":"KeyRecovery","abstract":[{"type":"text","text":"Information about the recover MPC keys containing key id String, Algorithm and KeyRecoveryStatus for each key"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/keyrecovery","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyRecovery","kind":"identifier"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/DeviceLogger":{"type":"topic","abstract":[{"type":"text","text":"The Fireblocks SDK does all of its logging through internal log handler."},{"type":"text","text":" "},{"type":"text","text":"It logs the messages into log files and exposes a URL to the logs as a zip file in the getURLForLogFiles function."},{"type":"text","text":" "},{"type":"text","text":"There are 6 log severity levels defined in the SDK:"},{"type":"text","text":" "},{"type":"text","text":"[LogLevel.none]"},{"type":"text","text":" "},{"type":"text","text":"[LogLevel.verbose]"},{"type":"text","text":" "},{"type":"text","text":"[LogLevel.debug]"},{"type":"text","text":" "},{"type":"text","text":"[LogLevel.info]"},{"type":"text","text":" "},{"type":"text","text":"[LogLevel.warn]"},{"type":"text","text":" "},{"type":"text","text":"[LogLevel.error]"}],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/DeviceLogger","title":"DeviceLogger","kind":"symbol","url":"\/documentation\/fireblockssdk\/devicelogger","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceLogger","kind":"identifier"}],"navigatorTitle":[{"text":"DeviceLogger","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyStatus":{"navigatorTitle":[{"kind":"identifier","text":"KeyStatus"}],"title":"KeyStatus","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/keystatus","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyStatus"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksError":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FireblocksError"}],"url":"\/documentation\/fireblockssdk\/fireblockserror","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FireblocksError"}],"title":"FireblocksError"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksSDKVersionString":{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksSDKVersionString","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Project version string for Fireblocks."}],"url":"\/documentation\/fireblockssdk\/fireblockssdkversionstring","fragments":[{"text":"FireblocksSDKVersionString","kind":"identifier"}],"title":"FireblocksSDKVersionString"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/DerivationParams":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/DerivationParams","kind":"symbol","title":"DerivationParams","url":"\/documentation\/fireblockssdk\/derivationparams","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DerivationParams","kind":"identifier"}],"navigatorTitle":[{"text":"DerivationParams","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyTakeoverStatus":{"navigatorTitle":[{"kind":"identifier","text":"KeyTakeoverStatus"}],"title":"KeyTakeoverStatus","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/keytakeoverstatus","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyTakeoverStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyTakeoverStatus"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyData":{"navigatorTitle":[{"kind":"identifier","text":"KeyData"}],"title":"KeyData","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/keydata","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyData"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/TransactionSignature":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/TransactionSignature","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransactionSignature"}],"url":"\/documentation\/fireblockssdk\/transactionsignature","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TransactionSignature"}],"title":"TransactionSignature"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Bridge":{"navigatorTitle":[{"kind":"identifier","text":"Bridge"}],"title":"Bridge","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/bridge","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Bridge","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bridge"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FullKey":{"navigatorTitle":[{"kind":"identifier","text":"FullKey"}],"title":"FullKey","abstract":[{"type":"text","text":"Information about the FullKey generated"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/fullkey","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullKey"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/DeviceStatus":{"role":"symbol","abstract":[{"type":"text","text":"The status of the Fireblocks SDK device"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/DeviceStatus","url":"\/documentation\/fireblockssdk\/devicestatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DeviceStatus"}],"title":"DeviceStatus","navigatorTitle":[{"kind":"identifier","text":"DeviceStatus"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor":{"kind":"symbol","title":"JoinWalletDescriptor","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinWalletDescriptor"}],"url":"\/documentation\/fireblockssdk\/joinwalletdescriptor","abstract":[{"text":"Information about the approval request to join an existing wallet or the join request to an existing wallet.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"JoinWalletDescriptor"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Env":{"role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Env","url":"\/documentation\/fireblockssdk\/env","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Env"}],"title":"Env","navigatorTitle":[{"text":"Env","kind":"identifier"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksPassphraseResolver":{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksPassphraseResolver","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"FireblocksPassphraseResolver","kind":"identifier"}],"abstract":[],"url":"\/documentation\/fireblockssdk\/fireblockspassphraseresolver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FireblocksPassphraseResolver","kind":"identifier"}],"title":"FireblocksPassphraseResolver"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyStorageDelegate":{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyStorageDelegate","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"KeyStorageDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Implement this delegate on your host app in order to handle and manage your own raw keys on your stroage"}],"url":"\/documentation\/fireblockssdk\/keystoragedelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyStorageDelegate","kind":"identifier"}],"title":"KeyStorageDelegate"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/TransactionSignatureStatus":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/TransactionSignatureStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransactionSignatureStatus"}],"url":"\/documentation\/fireblockssdk\/transactionsignaturestatus","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TransactionSignatureStatus"}],"title":"TransactionSignatureStatus"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/ReportingOptions":{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/ReportingOptions","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"ReportingOptions","kind":"identifier"}],"abstract":[],"url":"\/documentation\/fireblockssdk\/reportingoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReportingOptions","kind":"identifier"}],"title":"ReportingOptions"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecoveryStatus":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecoveryStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyRecoveryStatus","kind":"identifier"}],"url":"\/documentation\/fireblockssdk\/keyrecoverystatus","abstract":[],"navigatorTitle":[{"text":"KeyRecoveryStatus","kind":"identifier"}],"title":"KeyRecoveryStatus"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/ClearDevice":{"navigatorTitle":[{"text":"ClearDevice","kind":"identifier"}],"title":"ClearDevice","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/cleardevice","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/ClearDevice","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClearDevice","kind":"identifier"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Status":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Status","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"url":"\/documentation\/fireblockssdk\/status","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Status"}],"title":"Status"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyTakeover":{"navigatorTitle":[{"kind":"identifier","text":"KeyTakeover"}],"title":"KeyTakeover","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/keytakeover","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyTakeover","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeyTakeover"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyBackupStatus":{"navigatorTitle":[{"text":"KeyBackupStatus","kind":"identifier"}],"title":"KeyBackupStatus","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/keybackupstatus","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackupStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KeyBackupStatus"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksSDKVersionNumber":{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksSDKVersionNumber","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Project version number for Fireblocks."}],"url":"\/documentation\/fireblockssdk\/fireblockssdkversionnumber","fragments":[{"text":"FireblocksSDKVersionNumber","kind":"identifier"}],"title":"FireblocksSDKVersionNumber"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Algorithm":{"navigatorTitle":[{"text":"Algorithm","kind":"identifier"}],"title":"Algorithm","abstract":[{"text":"Supported Signature algorithms for MPC keys","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/algorithm","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Algorithm","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Algorithm"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery"],"generated":true,"anchor":"Classes"},{"title":"Variables","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksSDKVersionNumber","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksSDKVersionString"],"generated":true,"anchor":"Variables"},{"title":"Functions","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/tryBlock(_:)"],"generated":true,"anchor":"Functions"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1tryBlock(_:)\/title","value":"tryBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1tryBlock(_:)\/fragments","value":[{"text":"tryBlock","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/title","value":"KeyDescriptor"},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/fragments","value":[{"text":"KeyDescriptor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/navigatorTitle","value":[{"text":"KeyDescriptor","kind":"identifier"}]},{"op":"replace","value":"KeyBackup","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/title"},{"op":"replace","value":[{"text":"KeyBackup","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/fragments"},{"op":"replace","value":[{"text":"KeyBackup","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/navigatorTitle"},{"op":"replace","value":"KeyRecovery","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/title"},{"op":"replace","value":[{"text":"KeyRecovery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/fragments"},{"op":"replace","value":[{"text":"KeyRecovery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/navigatorTitle"},{"op":"replace","value":"FullKey","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/title"},{"op":"replace","value":[{"text":"FullKey","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/fragments"},{"op":"replace","value":[{"text":"FullKey","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/navigatorTitle"},{"op":"replace","value":"JoinWalletDescriptor","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/title"},{"op":"replace","value":[{"text":"JoinWalletDescriptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"JoinWalletDescriptor"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/navigatorTitle"}]}]}