{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"decoder"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor"]]},"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/init(from:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Initializer","modules":[{"name":"FireblocksSDK"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"externalID":"s:13FireblocksSDK13KeyDescriptorC4fromACs7Decoder_p_tKcfc","title":"init(from:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Decodable.init(from:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/keydescriptor\/init(from:)"]}],"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyStatus for each key"}],"kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor","url":"\/documentation\/fireblockssdk\/keydescriptor","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"KeyDescriptor","kind":"identifier"}],"title":"KeyDescriptor","navigatorTitle":[{"text":"KeyDescriptor","kind":"identifier"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyDescriptor/init(from:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyDescriptor\/init(from:)","title":"init(from:)","kind":"symbol","url":"\/documentation\/fireblockssdk\/keydescriptor\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/title","op":"replace","value":"KeyDescriptor"},{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/fragments","op":"replace","value":[{"kind":"identifier","text":"KeyDescriptor"}]},{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyDescriptor\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"KeyDescriptor"}]}]}]}