{"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/BackupProtocol-Implementations"]]},"metadata":{"extendedModule":"FireblocksSDK","roleHeading":"Instance Method","title":"backupKeys(passphrase:passphraseId:callback:)","externalID":"s:13FireblocksSDK0A0C10backupKeys10passphrase0E2Id8callbackySS_SSyShyAA9KeyBackupCGctKF","symbolKind":"method","modules":[{"name":"FireblocksSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backupKeys"},{"kind":"text","text":"("},{"kind":"externalParam","text":"passphrase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"passphraseId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyBackup","text":"KeyBackup"},{"kind":"text","text":">) -> ()) "},{"kind":"keyword","text":"throws"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backupKeys","kind":"identifier"},{"text":"(","kind":"text"},{"text":"passphrase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"passphraseId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyBackup","text":"KeyBackup","kind":"typeIdentifier"},{"text":">) -> ()) ","kind":"text"},{"text":"throws","kind":"keyword"}]}]},{"kind":"parameters","parameters":[{"name":"passphrase","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Passphrase In order to encrypt and backup the MPC key."},{"type":"text","text":" "},{"type":"text","text":"The passPhrase must be unique and secure. Use generateRandomPassphrase method."}]}]},{"name":"passphraseId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"passphraseId In order to identify the backed up MPC key."},{"type":"text","text":" "},{"type":"text","text":"The passphraseId must be unique and secure. Use generatePassphraseId method."}]}]},{"name":"callback","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Invoked with the Set of "},{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup","type":"reference","isActive":true},{"type":"text","text":" with the information of all backed up keys."}]}]}]}],"abstract":[{"type":"text","text":"Backup end-user keys to Fireblocks"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/fireblockssdk\/fireblocks\/backupkeys(passphrase:passphraseid:callback:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/backupKeys(passphrase:passphraseId:callback:)","interfaceLanguage":"swift"},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks":{"kind":"symbol","title":"Fireblocks","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fireblocks"}],"url":"\/documentation\/fireblockssdk\/fireblocks","abstract":[{"text":"The Fireblocks SDK main class. Use it to perform all of the SDK functionality.","type":"text"},{"text":" ","type":"text"},{"text":"Call Fireblocks.initialize to initialize the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Fireblocks"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/BackupProtocol-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/BackupProtocol-Implementations","url":"\/documentation\/fireblockssdk\/fireblocks\/backupprotocol-implementations","abstract":[],"title":"BackupProtocol Implementations"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyBackup":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyBackup","kind":"identifier"}],"url":"\/documentation\/fireblockssdk\/keybackup","abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyBackupStatus for each key"}],"navigatorTitle":[{"text":"KeyBackup","kind":"identifier"}],"title":"KeyBackup"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/backupKeys(passphrase:passphraseId:callback:)":{"type":"topic","abstract":[{"text":"Backup end-user keys to Fireblocks","type":"text"}],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/backupKeys(passphrase:passphraseId:callback:)","title":"backupKeys(passphrase:passphraseId:callback:)","kind":"symbol","url":"\/documentation\/fireblockssdk\/fireblocks\/backupkeys(passphrase:passphraseid:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backupKeys"},{"kind":"text","text":"("},{"kind":"externalParam","text":"passphrase"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"passphraseId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"KeyBackup","kind":"typeIdentifier","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyBackup"},{"text":">) -> ()) ","kind":"text"},{"kind":"keyword","text":"throws"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/title","op":"replace","value":"KeyBackup"},{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/fragments","op":"replace","value":[{"text":"KeyBackup","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/navigatorTitle","op":"replace","value":[{"text":"KeyBackup","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}