{"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/RecoveryProtocol-Implementations"]]},"metadata":{"externalID":"s:13FireblocksSDK0A0C11recoverKeys18passphraseResolver8callbackyAA0a10PassphraseF0_p_yShyAA11KeyRecoveryCGctKF","roleHeading":"Instance Method","title":"recoverKeys(passphraseResolver:callback:)","extendedModule":"FireblocksSDK","symbolKind":"method","modules":[{"name":"FireblocksSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverKeys"},{"kind":"text","text":"("},{"kind":"externalParam","text":"passphraseResolver"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13FireblocksSDK0A18PassphraseResolverP","kind":"typeIdentifier","text":"FireblocksPassphraseResolver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyRecovery","kind":"typeIdentifier","text":"KeyRecovery"},{"kind":"text","text":">) -> ()) "},{"kind":"keyword","text":"throws"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverKeys","kind":"identifier"},{"text":"(","kind":"text"},{"text":"passphraseResolver","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13FireblocksSDK0A18PassphraseResolverP","text":"FireblocksPassphraseResolver","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksPassphraseResolver","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyRecovery","text":"KeyRecovery","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery","kind":"typeIdentifier"},{"text":">) -> ()) ","kind":"text"},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"Invoked with the Set of ","type":"text"},{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery","isActive":true,"type":"reference"},{"text":" with the information of all backed up keys","type":"text"}],"type":"paragraph"}],"name":"callback"}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Recover an end-user key backup that was done using backupKeys"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/fireblocks\/recoverkeys(passphraseresolver:callback:)"]}],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/recoverKeys(passphraseResolver:callback:)","interfaceLanguage":"swift"},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksPassphraseResolver":{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksPassphraseResolver","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"FireblocksPassphraseResolver","kind":"identifier"}],"abstract":[],"url":"\/documentation\/fireblockssdk\/fireblockspassphraseresolver","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FireblocksPassphraseResolver","kind":"identifier"}],"title":"FireblocksPassphraseResolver"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks":{"kind":"symbol","title":"Fireblocks","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fireblocks"}],"url":"\/documentation\/fireblockssdk\/fireblocks","abstract":[{"text":"The Fireblocks SDK main class. Use it to perform all of the SDK functionality.","type":"text"},{"text":" ","type":"text"},{"text":"Call Fireblocks.initialize to initialize the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Fireblocks"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery":{"navigatorTitle":[{"text":"KeyRecovery","kind":"identifier"}],"title":"KeyRecovery","abstract":[{"type":"text","text":"Information about the recover MPC keys containing key id String, Algorithm and KeyRecoveryStatus for each key"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/keyrecovery","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyRecovery","kind":"identifier"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/recoverKeys(passphraseResolver:callback:)":{"title":"recoverKeys(passphraseResolver:callback:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/recoverKeys(passphraseResolver:callback:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverKeys","kind":"identifier"},{"text":"(","kind":"text"},{"text":"passphraseResolver","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FireblocksPassphraseResolver","kind":"typeIdentifier","preciseIdentifier":"s:13FireblocksSDK0A18PassphraseResolverP"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyRecovery","text":"KeyRecovery"},{"text":">) -> ()) ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/fireblockssdk\/fireblocks\/recoverkeys(passphraseresolver:callback:)","abstract":[{"type":"text","text":"Recover an end-user key backup that was done using backupKeys"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/RecoveryProtocol-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/RecoveryProtocol-Implementations","url":"\/documentation\/fireblockssdk\/fireblocks\/recoveryprotocol-implementations","abstract":[],"title":"RecoveryProtocol Implementations"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"KeyRecovery","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/title"},{"op":"replace","value":[{"text":"KeyRecovery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/fragments"},{"op":"replace","value":[{"text":"KeyRecovery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/navigatorTitle"}]}]}