{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"takeover","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"FullKey","kind":"typeIdentifier","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)FullKey"},{"text":">) -> ()) ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"callback","content":[{"inlineContent":[{"type":"text","text":"Set of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey"},{"type":"text","text":" that contains extended private key as xprv \/ fprv and an extended public key as xpub \/ fpub or a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksError"}],"type":"paragraph"}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/TakeoverProtocol-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/takeover(callback:)"},"metadata":{"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"FireblocksSDK"}],"extendedModule":"FireblocksSDK","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"takeover","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)FullKey","text":"FullKey","kind":"typeIdentifier"},{"text":">) -> ()) ","kind":"text"},{"text":"throws","kind":"keyword"}],"externalID":"s:13FireblocksSDK0A0C8takeover8callbackyyShyAA7FullKeyCGc_tKF","title":"takeover(callback:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Reconstructs all shares of a MPC key (mobile + cloud shares) into the full public and private keys"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/fireblocks\/takeover(callback:)"]}],"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksError":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FireblocksError"}],"url":"\/documentation\/fireblockssdk\/fireblockserror","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FireblocksError"}],"title":"FireblocksError"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/TakeoverProtocol-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/TakeoverProtocol-Implementations","url":"\/documentation\/fireblockssdk\/fireblocks\/takeoverprotocol-implementations","abstract":[],"title":"TakeoverProtocol Implementations"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks":{"kind":"symbol","title":"Fireblocks","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fireblocks"}],"url":"\/documentation\/fireblockssdk\/fireblocks","abstract":[{"text":"The Fireblocks SDK main class. Use it to perform all of the SDK functionality.","type":"text"},{"text":" ","type":"text"},{"text":"Call Fireblocks.initialize to initialize the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Fireblocks"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Fireblocks/takeover(callback:)":{"title":"takeover(callback:)","abstract":[{"type":"text","text":"Reconstructs all shares of a MPC key (mobile + cloud shares) into the full public and private keys"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/fireblocks\/takeover(callback:)","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Fireblocks\/takeover(callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"takeover"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)FullKey","text":"FullKey"},{"kind":"text","text":">) -> ()) "},{"kind":"keyword","text":"throws"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FullKey":{"navigatorTitle":[{"kind":"identifier","text":"FullKey"}],"title":"FullKey","abstract":[{"type":"text","text":"Information about the FullKey generated"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/fullkey","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullKey"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/title","value":"FullKey"},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/fragments","value":[{"text":"FullKey","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/navigatorTitle","value":[{"text":"FullKey","kind":"identifier"}]}]}]}