{"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AnyCodable","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/CoreOptions","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWallet","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletOptions"],"title":"Classes","anchor":"Classes"},{"generated":true,"identifiers":["doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AuthTokenRetriever","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletAccountsProtocol","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletAssetsProtocol","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletCoreProtocol","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletGetDeviceProtocol","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletNFTProtocol","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletTransactionsProtocol","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletWeb3ConnectionsProtocol"],"title":"Protocols","anchor":"Protocols"},{"generated":true,"identifiers":["doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Account","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AddressDetails","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AmlRegistrationResult","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AmlScreeningResult","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AmountInfo","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Asset","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AssetBalance","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AssignResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AuthorizationGroups","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AuthorizationInfo","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/BalanceRewardInfo","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/BlockInfo","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/ComplianceResult","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/ComplianceScreeningResult","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/CreateTransactionResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/CreateWeb3ConnectionResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/DestinationTransferPeerPath","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/DestinationTransferPeerPathResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Device","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EstimatedTransactionFeeResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/ExtraParameters","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/FeeInfo","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Input","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/InputsSelection","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/LatestBackupKey","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/LatestBackupResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/MediaEntityResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/NetworkRecord","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/NodeControls","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/OneTimeAddress","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/PaginatedResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Paging","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/PreHash","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/RawMessageData","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/RespondToConnectionRequest","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/RewardInfo","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SignedMessage","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SignedMessageSignature","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SourceTransferPeerPath","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SourceTransferPeerPathResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SpamOwnershipResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SpamTokenResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SuccessResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SystemMessageInfo","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TokenCollectionResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TokenOwnershipResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TokenResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionFee","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionRequest","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionRequestDestination","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionResponse","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionResponseContractCallDecodedData","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionResponseDestination","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TravelRuleCreateTransactionRequest","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TravelRuleOwnershipProof","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TravelRulePiiIVMS","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TravelRuleTransactionBlockchainInfo","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/UnsignedRawMessage","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3Connection","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3ConnectionRequest","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3ConnectionSessionMetadata","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3Filter"],"title":"Structures","anchor":"Structures"},{"generated":true,"identifiers":["doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AddressState","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AddressType","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/BlockchainDescriptor","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/DestType","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Direction","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletEnvironment","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletException","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/ErrorCodes","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/FeeLevel","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/GetOwnershipTokensSort","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/GetTransactionOperation","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/ListOwnedTokensSort","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Order","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/OrderBy","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/ScreeningStatus","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SourceType","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Status","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TokensSpam","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TokensStatus","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionOperation","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransferPeerPathSubType","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransferPeerPathType","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3ConnectionFeeLevel","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3ConnectionMethod","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3ConnectionSort","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3ConnectionType"],"title":"Enumerations","anchor":"Enumerations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/embeddedwalletsdk"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/embeddedwalletsdk"]}],"hierarchy":{"paths":[[]]},"metadata":{"symbolKind":"module","role":"collection","roleHeading":"Framework","modules":[{"name":"EmbeddedWalletSDK"}],"title":"EmbeddedWalletSDK","externalID":"EmbeddedWalletSDK"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TokensSpam":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/tokensspam","navigatorTitle":[{"text":"TokensSpam","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TokensSpam","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TokensSpam","title":"TokensSpam","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/UnsignedRawMessage":{"title":"UnsignedRawMessage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnsignedRawMessage"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/UnsignedRawMessage","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/unsignedrawmessage","role":"symbol","type":"topic","abstract":[{"text":"A model representing the data required for signing a transaction or message, including the content to sign, BIP44 address index, change path, and optional derivation path details.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"UnsignedRawMessage"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/AuthorizationInfo":{"title":"AuthorizationInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthorizationInfo"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AuthorizationInfo","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/authorizationinfo","role":"symbol","type":"topic","abstract":[{"text":"A model representing the information about your ","type":"text"},{"isActive":true,"identifier":"https:\/\/developers.fireblocks.com\/docs\/capabilities#transaction-authorization-policy-tap","type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AuthorizationInfo"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EmbeddedWalletAccountsProtocol":{"title":"EmbeddedWalletAccountsProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmbeddedWalletAccountsProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletAccountsProtocol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/embeddedwalletaccountsprotocol","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"EmbeddedWalletAccountsProtocol","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EmbeddedWalletOptions":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmbeddedWalletOptions","kind":"identifier"}],"title":"EmbeddedWalletOptions","url":"\/documentation\/embeddedwalletsdk\/embeddedwalletoptions","kind":"symbol","type":"topic","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletOptions","navigatorTitle":[{"text":"EmbeddedWalletOptions","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TransactionResponse":{"title":"TransactionResponse","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransactionResponse"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionResponse","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/transactionresponse","role":"symbol","type":"topic","abstract":[{"text":"A model representing the response of a transaction, including transaction details such as IDs, status, operation type, fees, and more.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TransactionResponse"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EmbeddedWalletSDKVersionNumber":{"abstract":[{"type":"text","text":"Project version number for EmbeddedWalletSDK."}],"fragments":[{"text":"EmbeddedWalletSDKVersionNumber","kind":"identifier"}],"title":"EmbeddedWalletSDKVersionNumber","url":"\/documentation\/embeddedwalletsdk\/embeddedwalletsdkversionnumber","kind":"symbol","type":"topic","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletSDKVersionNumber","role":"symbol"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Account":{"title":"Account","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Account"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Account","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/account","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Account"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TravelRulePiiIVMS":{"title":"TravelRulePiiIVMS","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelRulePiiIVMS","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TravelRulePiiIVMS","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/travelrulepiiivms","role":"symbol","type":"topic","abstract":[{"text":"A model representing the Personally Identifiable Information (PII) for a Travel Rule IVMS (International Virtual Monetary System) transaction.","type":"text"}],"navigatorTitle":[{"text":"TravelRulePiiIVMS","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/ExtraParameters":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/extraparameters","navigatorTitle":[{"kind":"identifier","text":"ExtraParameters"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExtraParameters"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/ExtraParameters","title":"ExtraParameters","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/DestinationTransferPeerPath":{"title":"DestinationTransferPeerPath","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DestinationTransferPeerPath","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/DestinationTransferPeerPath","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/destinationtransferpeerpath","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A model representing the destination details of a transaction."}],"navigatorTitle":[{"text":"DestinationTransferPeerPath","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/DestType":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/desttype","navigatorTitle":[{"kind":"identifier","text":"DestType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestType"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/DestType","title":"DestType","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/SourceTransferPeerPath":{"title":"SourceTransferPeerPath","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SourceTransferPeerPath"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SourceTransferPeerPath","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/sourcetransferpeerpath","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A model representing the source details of a transaction."}],"navigatorTitle":[{"kind":"identifier","text":"SourceTransferPeerPath"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/AssetBalance":{"title":"AssetBalance","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AssetBalance","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AssetBalance","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/assetbalance","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A model representing the balance details of an asset, including available, pending, and frozen amounts, as well as block information and reward data."}],"navigatorTitle":[{"text":"AssetBalance","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EmbeddedWalletWeb3ConnectionsProtocol":{"navigatorTitle":[{"text":"EmbeddedWalletWeb3ConnectionsProtocol","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletWeb3ConnectionsProtocol","title":"EmbeddedWalletWeb3ConnectionsProtocol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmbeddedWalletWeb3ConnectionsProtocol","kind":"identifier"}],"url":"\/documentation\/embeddedwalletsdk\/embeddedwalletweb3connectionsprotocol","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/ScreeningStatus":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/screeningstatus","navigatorTitle":[{"kind":"identifier","text":"ScreeningStatus"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScreeningStatus"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/ScreeningStatus","title":"ScreeningStatus","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/NodeControls":{"abstract":[{"type":"text","text":"A model to configure special node requirements."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NodeControls","kind":"identifier"}],"title":"NodeControls","url":"\/documentation\/embeddedwalletsdk\/nodecontrols","kind":"symbol","type":"topic","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/NodeControls","navigatorTitle":[{"text":"NodeControls","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Web3ConnectionSort":{"title":"Web3ConnectionSort","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Web3ConnectionSort"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3ConnectionSort","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/web3connectionsort","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Web3ConnectionSort"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Status":{"title":"Status","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Status","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/status","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"Status","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TokensStatus":{"title":"TokensStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TokensStatus"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TokensStatus","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/tokensstatus","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TokensStatus"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/FeeLevel":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/feelevel","navigatorTitle":[{"kind":"identifier","text":"FeeLevel"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeeLevel"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/FeeLevel","title":"FeeLevel","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/ListOwnedTokensSort":{"title":"ListOwnedTokensSort","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ListOwnedTokensSort"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/ListOwnedTokensSort","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/listownedtokenssort","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ListOwnedTokensSort"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/AmlRegistrationResult":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AmlRegistrationResult","kind":"identifier"}],"title":"AmlRegistrationResult","url":"\/documentation\/embeddedwalletsdk\/amlregistrationresult","kind":"symbol","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AmlRegistrationResult","type":"topic","navigatorTitle":[{"text":"AmlRegistrationResult","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/CreateWeb3ConnectionResponse":{"navigatorTitle":[{"text":"CreateWeb3ConnectionResponse","kind":"identifier"}],"type":"topic","role":"symbol","title":"CreateWeb3ConnectionResponse","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/CreateWeb3ConnectionResponse","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateWeb3ConnectionResponse","kind":"identifier"}],"url":"\/documentation\/embeddedwalletsdk\/createweb3connectionresponse","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/ErrorCodes":{"navigatorTitle":[{"text":"ErrorCodes","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/ErrorCodes","title":"ErrorCodes","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorCodes","kind":"identifier"}],"url":"\/documentation\/embeddedwalletsdk\/errorcodes","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EmbeddedWalletAssetsProtocol":{"title":"EmbeddedWalletAssetsProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmbeddedWalletAssetsProtocol"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletAssetsProtocol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/embeddedwalletassetsprotocol","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"EmbeddedWalletAssetsProtocol"}]},"https://developers.fireblocks.com/docs/capabilities#transaction-authorization-policy-tap":{"url":"https:\/\/developers.fireblocks.com\/docs\/capabilities#transaction-authorization-policy-tap","type":"link","titleInlineContent":[{"type":"text","text":"Transaction Authorization Policy (TAP)"}],"identifier":"https:\/\/developers.fireblocks.com\/docs\/capabilities#transaction-authorization-policy-tap","title":"Transaction Authorization Policy (TAP)"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/SourceTransferPeerPathResponse":{"navigatorTitle":[{"text":"SourceTransferPeerPathResponse","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SourceTransferPeerPathResponse","title":"SourceTransferPeerPathResponse","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceTransferPeerPathResponse","kind":"identifier"}],"url":"\/documentation\/embeddedwalletsdk\/sourcetransferpeerpathresponse","abstract":[{"text":"A model representing the source of the transaction.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Web3ConnectionType":{"navigatorTitle":[{"text":"Web3ConnectionType","kind":"identifier"}],"type":"topic","role":"symbol","title":"Web3ConnectionType","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3ConnectionType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Web3ConnectionType","kind":"identifier"}],"url":"\/documentation\/embeddedwalletsdk\/web3connectiontype","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Web3ConnectionFeeLevel":{"title":"Web3ConnectionFeeLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Web3ConnectionFeeLevel"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3ConnectionFeeLevel","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/web3connectionfeelevel","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Web3ConnectionFeeLevel"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TransactionRequestDestination":{"title":"TransactionRequestDestination","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransactionRequestDestination","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionRequestDestination","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/transactionrequestdestination","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"TransactionRequestDestination","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/AuthTokenRetriever":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthTokenRetriever","kind":"identifier"}],"title":"AuthTokenRetriever","url":"\/documentation\/embeddedwalletsdk\/authtokenretriever","kind":"symbol","type":"topic","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AuthTokenRetriever","navigatorTitle":[{"text":"AuthTokenRetriever","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/RawMessageData":{"abstract":[{"type":"text","text":"A model representing the data required for signing messages."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawMessageData","kind":"identifier"}],"title":"RawMessageData","url":"\/documentation\/embeddedwalletsdk\/rawmessagedata","kind":"symbol","type":"topic","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/RawMessageData","navigatorTitle":[{"text":"RawMessageData","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/FeeInfo":{"abstract":[{"type":"text","text":"A model representing the details of the transaction’s fee."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeeInfo","kind":"identifier"}],"title":"FeeInfo","url":"\/documentation\/embeddedwalletsdk\/feeinfo","kind":"symbol","type":"topic","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/FeeInfo","navigatorTitle":[{"text":"FeeInfo","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Order":{"title":"Order","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Order","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Order","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/order","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"Order","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TransactionOperation":{"title":"TransactionOperation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransactionOperation"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionOperation","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/transactionoperation","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"TransactionOperation","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EmbeddedWalletEnvironment":{"title":"EmbeddedWalletEnvironment","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmbeddedWalletEnvironment","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletEnvironment","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/embeddedwalletenvironment","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"EmbeddedWalletEnvironment","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/AnyCodable":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/anycodable","navigatorTitle":[{"kind":"identifier","text":"AnyCodable"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnyCodable"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AnyCodable","title":"AnyCodable","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/RespondToConnectionRequest":{"navigatorTitle":[{"text":"RespondToConnectionRequest","kind":"identifier"}],"type":"topic","role":"symbol","title":"RespondToConnectionRequest","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/RespondToConnectionRequest","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RespondToConnectionRequest","kind":"identifier"}],"url":"\/documentation\/embeddedwalletsdk\/respondtoconnectionrequest","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EmbeddedWalletNFTProtocol":{"title":"EmbeddedWalletNFTProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmbeddedWalletNFTProtocol"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletNFTProtocol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/embeddedwalletnftprotocol","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"EmbeddedWalletNFTProtocol"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/AmountInfo":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/amountinfo","navigatorTitle":[{"text":"AmountInfo","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AmountInfo","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AmountInfo","title":"AmountInfo","abstract":[{"text":"A model representing the details of the requested amount to transfer.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Web3Connection":{"navigatorTitle":[{"text":"Web3Connection","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3Connection","title":"Web3Connection","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Web3Connection","kind":"identifier"}],"url":"\/documentation\/embeddedwalletsdk\/web3connection","abstract":[{"text":"A model representing the requested dApp connection’s data.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/RewardInfo":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/rewardinfo","navigatorTitle":[{"text":"RewardInfo","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RewardInfo","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/RewardInfo","title":"RewardInfo","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/SignedMessage":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/signedmessage","navigatorTitle":[{"kind":"identifier","text":"SignedMessage"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignedMessage"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SignedMessage","title":"SignedMessage","abstract":[{"text":"A model representing a signed message, which includes the content, algorithm, derivation path, signature, and public key.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EstimatedTransactionFeeResponse":{"title":"EstimatedTransactionFeeResponse","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EstimatedTransactionFeeResponse","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EstimatedTransactionFeeResponse","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/estimatedtransactionfeeresponse","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A model representing the estimated transaction fees for different fee levels."}],"navigatorTitle":[{"kind":"identifier","text":"EstimatedTransactionFeeResponse"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/BlockInfo":{"title":"BlockInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockInfo"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/BlockInfo","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/blockinfo","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"BlockInfo"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EmbeddedWalletCoreProtocol":{"title":"EmbeddedWalletCoreProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmbeddedWalletCoreProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletCoreProtocol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/embeddedwalletcoreprotocol","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"EmbeddedWalletCoreProtocol","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/SpamTokenResponse":{"title":"SpamTokenResponse","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SpamTokenResponse","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SpamTokenResponse","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/spamtokenresponse","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"SpamTokenResponse","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TravelRuleCreateTransactionRequest":{"navigatorTitle":[{"text":"TravelRuleCreateTransactionRequest","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TravelRuleCreateTransactionRequest","title":"TravelRuleCreateTransactionRequest","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelRuleCreateTransactionRequest","kind":"identifier"}],"url":"\/documentation\/embeddedwalletsdk\/travelrulecreatetransactionrequest","abstract":[{"text":"A model representing the information required to create a Travel Rule transaction request.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TokenResponse":{"title":"TokenResponse","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"TokenResponse","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TokenResponse","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/tokenresponse","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A model representing a token response."}],"navigatorTitle":[{"text":"TokenResponse","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TokenOwnershipResponse":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/tokenownershipresponse","navigatorTitle":[{"kind":"identifier","text":"TokenOwnershipResponse"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TokenOwnershipResponse"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TokenOwnershipResponse","title":"TokenOwnershipResponse","abstract":[{"text":"A model representing the details of an owned token.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TransactionResponseContractCallDecodedData":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/transactionresponsecontractcalldecodeddata","navigatorTitle":[{"kind":"identifier","text":"TransactionResponseContractCallDecodedData"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransactionResponseContractCallDecodedData"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionResponseContractCallDecodedData","title":"TransactionResponseContractCallDecodedData","abstract":[{"type":"text","text":"A model representing the decoded data for "},{"type":"codeVoice","code":"CONTRACT_CALL"},{"type":"text","text":" operations."}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/LatestBackupKey":{"title":"LatestBackupKey","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LatestBackupKey"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/LatestBackupKey","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/latestbackupkey","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A model representing the key information for the latest backup, including the device ID, key ID, public key, and the key’s algorithm."}],"navigatorTitle":[{"kind":"identifier","text":"LatestBackupKey"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Asset":{"navigatorTitle":[{"kind":"identifier","text":"Asset"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Asset","title":"Asset","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Asset"}],"url":"\/documentation\/embeddedwalletsdk\/asset","abstract":[{"text":"A model representing details of an asset.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/ComplianceScreeningResult":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComplianceScreeningResult","kind":"identifier"}],"title":"ComplianceScreeningResult","url":"\/documentation\/embeddedwalletsdk\/compliancescreeningresult","kind":"symbol","type":"topic","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/ComplianceScreeningResult","navigatorTitle":[{"text":"ComplianceScreeningResult","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EmbeddedWalletException":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/embeddedwalletexception","navigatorTitle":[{"kind":"identifier","text":"EmbeddedWalletException"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmbeddedWalletException"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletException","title":"EmbeddedWalletException","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EmbeddedWalletGetDeviceProtocol":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmbeddedWalletGetDeviceProtocol","kind":"identifier"}],"title":"EmbeddedWalletGetDeviceProtocol","url":"\/documentation\/embeddedwalletsdk\/embeddedwalletgetdeviceprotocol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletGetDeviceProtocol","navigatorTitle":[{"text":"EmbeddedWalletGetDeviceProtocol","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/PreHash":{"title":"PreHash","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreHash"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/PreHash","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/prehash","role":"symbol","type":"topic","abstract":[{"text":"A model representing pre-hashed content along with the hashing algorithm used.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PreHash"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TravelRuleTransactionBlockchainInfo":{"title":"TravelRuleTransactionBlockchainInfo","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelRuleTransactionBlockchainInfo","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TravelRuleTransactionBlockchainInfo","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/travelruletransactionblockchaininfo","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A model representing the blockchain information for a Travel Rule transaction."}],"navigatorTitle":[{"text":"TravelRuleTransactionBlockchainInfo","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EmbeddedWallet":{"title":"EmbeddedWallet","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmbeddedWallet"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWallet","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/embeddedwallet","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"EmbeddedWallet"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EmbeddedWalletSDKVersionString":{"abstract":[{"type":"text","text":"Project version string for EmbeddedWalletSDK."}],"fragments":[{"text":"EmbeddedWalletSDKVersionString","kind":"identifier"}],"title":"EmbeddedWalletSDKVersionString","url":"\/documentation\/embeddedwalletsdk\/embeddedwalletsdkversionstring","kind":"symbol","type":"topic","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletSDKVersionString","role":"symbol"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/SignedMessageSignature":{"title":"SignedMessageSignature","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignedMessageSignature","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SignedMessageSignature","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/signedmessagesignature","role":"symbol","type":"topic","abstract":[{"text":"A model representing the signature of a signed message, including the full signature and its components.","type":"text"}],"navigatorTitle":[{"text":"SignedMessageSignature","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/BalanceRewardInfo":{"title":"BalanceRewardInfo","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BalanceRewardInfo","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/BalanceRewardInfo","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/balancerewardinfo","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A model representing the reward information associated with a balance, including the pending rewards."}],"navigatorTitle":[{"text":"BalanceRewardInfo","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/DestinationTransferPeerPathResponse":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/destinationtransferpeerpathresponse","navigatorTitle":[{"kind":"identifier","text":"DestinationTransferPeerPathResponse"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DestinationTransferPeerPathResponse"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/DestinationTransferPeerPathResponse","title":"DestinationTransferPeerPathResponse","abstract":[{"type":"text","text":"A model representing the destination of the transaction."}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TransactionResponseDestination":{"title":"TransactionResponseDestination","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransactionResponseDestination","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionResponseDestination","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/transactionresponsedestination","role":"symbol","type":"topic","abstract":[{"text":"A model representing the destination details of a transaction response.","type":"text"}],"navigatorTitle":[{"text":"TransactionResponseDestination","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TransactionFee":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/transactionfee","navigatorTitle":[{"kind":"identifier","text":"TransactionFee"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransactionFee"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionFee","title":"TransactionFee","abstract":[{"text":"A model representing the transaction fee details for various blockchain networks.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/CoreOptions":{"title":"CoreOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreOptions","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/CoreOptions","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/coreoptions","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"CoreOptions","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/SpamOwnershipResponse":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SpamOwnershipResponse","kind":"identifier"}],"title":"SpamOwnershipResponse","url":"\/documentation\/embeddedwalletsdk\/spamownershipresponse","kind":"symbol","type":"topic","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SpamOwnershipResponse","navigatorTitle":[{"text":"SpamOwnershipResponse","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/SuccessResponse":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/successresponse","navigatorTitle":[{"kind":"identifier","text":"SuccessResponse"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SuccessResponse"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SuccessResponse","title":"SuccessResponse","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TransferPeerPathSubType":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/transferpeerpathsubtype","navigatorTitle":[{"text":"TransferPeerPathSubType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransferPeerPathSubType","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransferPeerPathSubType","title":"TransferPeerPathSubType","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Web3ConnectionMethod":{"title":"Web3ConnectionMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Web3ConnectionMethod"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3ConnectionMethod","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/web3connectionmethod","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Web3ConnectionMethod"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/AuthorizationGroups":{"navigatorTitle":[{"text":"AuthorizationGroups","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AuthorizationGroups","title":"AuthorizationGroups","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthorizationGroups","kind":"identifier"}],"url":"\/documentation\/embeddedwalletsdk\/authorizationgroups","abstract":[{"text":"A model representing the groups of entities that can approve a transaction.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/AmlScreeningResult":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AmlScreeningResult","kind":"identifier"}],"title":"AmlScreeningResult","url":"\/documentation\/embeddedwalletsdk\/amlscreeningresult","kind":"symbol","type":"topic","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AmlScreeningResult","navigatorTitle":[{"text":"AmlScreeningResult","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Paging":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/paging","navigatorTitle":[{"text":"Paging","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Paging","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Paging","title":"Paging","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/SourceType":{"navigatorTitle":[{"text":"SourceType","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SourceType","title":"SourceType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SourceType","kind":"identifier"}],"url":"\/documentation\/embeddedwalletsdk\/sourcetype","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/GetTransactionOperation":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/gettransactionoperation","navigatorTitle":[{"text":"GetTransactionOperation","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetTransactionOperation","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/GetTransactionOperation","title":"GetTransactionOperation","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/PaginatedResponse":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/paginatedresponse","navigatorTitle":[{"text":"PaginatedResponse","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaginatedResponse","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/PaginatedResponse","title":"PaginatedResponse","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/OrderBy":{"title":"OrderBy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OrderBy"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/OrderBy","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/orderby","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"OrderBy"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/EmbeddedWalletTransactionsProtocol":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmbeddedWalletTransactionsProtocol","kind":"identifier"}],"title":"EmbeddedWalletTransactionsProtocol","url":"\/documentation\/embeddedwalletsdk\/embeddedwallettransactionsprotocol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletTransactionsProtocol","navigatorTitle":[{"text":"EmbeddedWalletTransactionsProtocol","kind":"identifier"}],"role":"symbol"},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TransactionRequest":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/transactionrequest","navigatorTitle":[{"kind":"identifier","text":"TransactionRequest"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransactionRequest"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransactionRequest","title":"TransactionRequest","abstract":[{"text":"A model representing the request for a transaction to be processed.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TransferPeerPathType":{"title":"TransferPeerPathType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TransferPeerPathType","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TransferPeerPathType","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/transferpeerpathtype","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TransferPeerPathType"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK":{"type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/embeddedwalletsdk","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK","title":"EmbeddedWalletSDK","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/InputsSelection":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/inputsselection","navigatorTitle":[{"kind":"identifier","text":"InputsSelection"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputsSelection"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/InputsSelection","title":"InputsSelection","abstract":[{"text":"A model representing selections of inputs for a transaction on UTXO-based blockchains.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/BlockchainDescriptor":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/blockchaindescriptor","navigatorTitle":[{"kind":"identifier","text":"BlockchainDescriptor"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockchainDescriptor"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/BlockchainDescriptor","title":"BlockchainDescriptor","abstract":[{"type":"text","text":"BlockchainDescriptor"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Device":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/device","navigatorTitle":[{"text":"Device","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Device","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Device","title":"Device","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/GetOwnershipTokensSort":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/getownershiptokenssort","navigatorTitle":[{"text":"GetOwnershipTokensSort","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GetOwnershipTokensSort","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/GetOwnershipTokensSort","title":"GetOwnershipTokensSort","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Web3Filter":{"title":"Web3Filter","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Web3Filter"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3Filter","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/web3filter","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents the filter criteria for querying Web3 connections."}],"navigatorTitle":[{"kind":"identifier","text":"Web3Filter"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/AddressState":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/addressstate","navigatorTitle":[{"text":"AddressState","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AddressState","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AddressState","title":"AddressState","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/MediaEntityResponse":{"navigatorTitle":[{"text":"MediaEntityResponse","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/MediaEntityResponse","title":"MediaEntityResponse","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MediaEntityResponse","kind":"identifier"}],"url":"\/documentation\/embeddedwalletsdk\/mediaentityresponse","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Web3ConnectionRequest":{"title":"Web3ConnectionRequest","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Web3ConnectionRequest","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3ConnectionRequest","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/web3connectionrequest","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"Web3ConnectionRequest","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/AddressDetails":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/addressdetails","navigatorTitle":[{"text":"AddressDetails","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AddressDetails","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AddressDetails","title":"AddressDetails","abstract":[{"text":"A model representing details of an address.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/NetworkRecord":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/networkrecord","navigatorTitle":[{"kind":"identifier","text":"NetworkRecord"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkRecord"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/NetworkRecord","title":"NetworkRecord","abstract":[{"text":"A model representing a network record for a transaction. This is used when a single transaction results in multiple transfers, such as a contract call.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/AddressType":{"navigatorTitle":[{"kind":"identifier","text":"AddressType"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AddressType","title":"AddressType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressType"}],"url":"\/documentation\/embeddedwalletsdk\/addresstype","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Direction":{"title":"Direction","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Direction"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Direction","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/direction","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Direction"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TravelRuleOwnershipProof":{"title":"TravelRuleOwnershipProof","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelRuleOwnershipProof","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TravelRuleOwnershipProof","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/travelruleownershipproof","role":"symbol","type":"topic","abstract":[{"text":"A model representing the ownership proof information in the Travel Rule.","type":"text"}],"navigatorTitle":[{"text":"TravelRuleOwnershipProof","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Web3ConnectionSessionMetadata":{"navigatorTitle":[{"text":"Web3ConnectionSessionMetadata","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Web3ConnectionSessionMetadata","title":"Web3ConnectionSessionMetadata","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Web3ConnectionSessionMetadata"}],"url":"\/documentation\/embeddedwalletsdk\/web3connectionsessionmetadata","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/LatestBackupResponse":{"title":"LatestBackupResponse","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LatestBackupResponse"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/LatestBackupResponse","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/latestbackupresponse","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A model representing the response for the latest backup, including the passphrase ID, creation time, and the backed-up keys."}],"navigatorTitle":[{"kind":"identifier","text":"LatestBackupResponse"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/OneTimeAddress":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/onetimeaddress","navigatorTitle":[{"kind":"identifier","text":"OneTimeAddress"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OneTimeAddress"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/OneTimeAddress","title":"OneTimeAddress","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/Input":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/input","navigatorTitle":[{"kind":"identifier","text":"Input"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Input"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/Input","title":"Input","abstract":[{"text":"A model representing an input in a transaction, containing the transaction hash and the UTXO index.","type":"text"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/ComplianceResult":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/complianceresult","navigatorTitle":[{"kind":"identifier","text":"ComplianceResult"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComplianceResult"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/ComplianceResult","title":"ComplianceResult","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/AssignResponse":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/assignresponse","navigatorTitle":[{"kind":"identifier","text":"AssignResponse"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AssignResponse"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/AssignResponse","title":"AssignResponse","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/SystemMessageInfo":{"navigatorTitle":[{"text":"SystemMessageInfo","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/SystemMessageInfo","title":"SystemMessageInfo","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SystemMessageInfo","kind":"identifier"}],"url":"\/documentation\/embeddedwalletsdk\/systemmessageinfo","abstract":[]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/TokenCollectionResponse":{"title":"TokenCollectionResponse","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TokenCollectionResponse","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/TokenCollectionResponse","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/tokencollectionresponse","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"TokenCollectionResponse","kind":"identifier"}]},"doc://com.fireblocks.EmbeddedWalletSDK/documentation/EmbeddedWalletSDK/CreateTransactionResponse":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/embeddedwalletsdk\/createtransactionresponse","navigatorTitle":[{"text":"CreateTransactionResponse","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CreateTransactionResponse","kind":"identifier"}],"identifier":"doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/CreateTransactionResponse","title":"CreateTransactionResponse","abstract":[{"type":"text","text":"A model representing the response details of a created transaction."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Variables","identifiers":["doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletSDKVersionNumber","doc:\/\/com.fireblocks.EmbeddedWalletSDK\/documentation\/EmbeddedWalletSDK\/EmbeddedWalletSDKVersionString"],"generated":true,"title":"Variables"}]},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null}]}]}