{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/joinwalletdescriptor\/requestid"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/requestId"},"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor"]]},"metadata":{"externalID":"s:13FireblocksSDK20JoinWalletDescriptorC9requestIdSSSgvp","roleHeading":"Instance Property","title":"requestId","symbolKind":"property","modules":[{"name":"FireblocksSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor":{"kind":"symbol","title":"JoinWalletDescriptor","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinWalletDescriptor"}],"url":"\/documentation\/fireblockssdk\/joinwalletdescriptor","abstract":[{"text":"Information about the approval request to join an existing wallet or the join request to an existing wallet.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"JoinWalletDescriptor"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor/requestId":{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/requestId","kind":"symbol","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/fireblockssdk\/joinwalletdescriptor\/requestid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"requestId"}},"variantOverrides":[{"patch":[{"op":"replace","value":"JoinWalletDescriptor","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/title"},{"op":"replace","value":[{"text":"JoinWalletDescriptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/fragments"},{"op":"replace","value":[{"text":"JoinWalletDescriptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}