{"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor"]]},"metadata":{"externalID":"s:13FireblocksSDK20JoinWalletDescriptorC4fromACs7Decoder_p_tKcfc","roleHeading":"Initializer","symbolKind":"init","title":"init(from:)","modules":[{"name":"FireblocksSDK"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"decoder","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"Decodable.init(from:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/fireblockssdk\/joinwalletdescriptor\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/init(from:)","interfaceLanguage":"swift"},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor":{"kind":"symbol","title":"JoinWalletDescriptor","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinWalletDescriptor"}],"url":"\/documentation\/fireblockssdk\/joinwalletdescriptor","abstract":[{"text":"Information about the approval request to join an existing wallet or the join request to an existing wallet.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"JoinWalletDescriptor"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor/init(from:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/init(from:)","title":"init(from:)","kind":"symbol","url":"\/documentation\/fireblockssdk\/joinwalletdescriptor\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/title","value":"JoinWalletDescriptor"},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/fragments","value":[{"text":"JoinWalletDescriptor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/navigatorTitle","value":[{"text":"JoinWalletDescriptor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}