{"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor"]]},"metadata":{"externalID":"s:13FireblocksSDK20JoinWalletDescriptorC6statusAA0cD6StatusOSgvp","roleHeading":"Instance Property","symbolKind":"property","title":"status","modules":[{"name":"FireblocksSDK"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13FireblocksSDK16JoinWalletStatusO","text":"JoinWalletStatus"},{"text":"?","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletStatus","preciseIdentifier":"s:13FireblocksSDK16JoinWalletStatusO","text":"JoinWalletStatus","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}]}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/joinwalletdescriptor\/status"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/status"},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor/status":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/status","title":"status","kind":"symbol","url":"\/documentation\/fireblockssdk\/joinwalletdescriptor\/status","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13FireblocksSDK16JoinWalletStatusO","text":"JoinWalletStatus","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletStatus":{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletStatus","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"JoinWalletStatus","kind":"identifier"}],"abstract":[],"url":"\/documentation\/fireblockssdk\/joinwalletstatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoinWalletStatus","kind":"identifier"}],"title":"JoinWalletStatus"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor":{"kind":"symbol","title":"JoinWalletDescriptor","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinWalletDescriptor"}],"url":"\/documentation\/fireblockssdk\/joinwalletdescriptor","abstract":[{"text":"Information about the approval request to join an existing wallet or the join request to an existing wallet.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"JoinWalletDescriptor"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/title","op":"replace","value":"JoinWalletDescriptor"},{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/fragments","op":"replace","value":[{"kind":"identifier","text":"JoinWalletDescriptor"}]},{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JoinWalletDescriptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}