{"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey"]]},"metadata":{"externalID":"s:13FireblocksSDK7FullKeyC5keyIdSSSgvp","roleHeading":"Instance Property","title":"keyId","symbolKind":"property","modules":[{"name":"FireblocksSDK"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/fullkey\/keyid"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/keyId"},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FullKey":{"navigatorTitle":[{"kind":"identifier","text":"FullKey"}],"title":"FullKey","abstract":[{"type":"text","text":"Information about the FullKey generated"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/fullkey","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FullKey"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FullKey/keyId":{"title":"keyId","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/fullkey\/keyid","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FullKey\/keyId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"FullKey","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/title"},{"op":"replace","value":[{"text":"FullKey","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"FullKey"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1FullKey\/navigatorTitle"}]}]}