{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoinWalletDescriptor","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor"},"abstract":[{"type":"text","text":"Information about the approval request to join an existing wallet or the join request to an existing wallet."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/init(from:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/algorithm","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/provisionKeyId","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/requestId","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/status"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/description()"],"generated":true,"anchor":"Instance-Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/Identifiable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(pl)NSObject","doc:\/\/com.fireblocks.Fireblocks\/s7CVarArgP","doc:\/\/com.fireblocks.Fireblocks\/s28CustomDebugStringConvertibleP","doc:\/\/com.fireblocks.Fireblocks\/s23CustomStringConvertibleP","doc:\/\/com.fireblocks.Fireblocks\/Se","doc:\/\/com.fireblocks.Fireblocks\/SE","doc:\/\/com.fireblocks.Fireblocks\/SQ","doc:\/\/com.fireblocks.Fireblocks\/SH","doc:\/\/com.fireblocks.Fireblocks\/s12IdentifiableP"],"kind":"relationships","type":"conformsTo"}],"metadata":{"externalID":"c:@M@FireblocksSDK@objc(cs)JoinWalletDescriptor","title":"JoinWalletDescriptor","roleHeading":"Class","modules":[{"name":"FireblocksSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoinWalletDescriptor","kind":"identifier"}],"navigatorTitle":[{"text":"JoinWalletDescriptor","kind":"identifier"}],"role":"symbol","symbolKind":"class"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/joinwalletdescriptor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/fireblockssdk\/joinwalletdescriptor"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor/status":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/status","title":"status","kind":"symbol","url":"\/documentation\/fireblockssdk\/joinwalletdescriptor\/status","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13FireblocksSDK16JoinWalletStatusO","text":"JoinWalletStatus","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.fireblocks.Fireblocks/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SQ"},"doc://com.fireblocks.Fireblocks/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s7CVarArgP"},"doc://com.fireblocks.Fireblocks/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor":{"kind":"symbol","title":"JoinWalletDescriptor","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinWalletDescriptor"}],"url":"\/documentation\/fireblockssdk\/joinwalletdescriptor","abstract":[{"text":"Information about the approval request to join an existing wallet or the join request to an existing wallet.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"JoinWalletDescriptor"}],"type":"topic"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor/provisionKeyId":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/provisionKeyId","title":"provisionKeyId","kind":"symbol","url":"\/documentation\/fireblockssdk\/joinwalletdescriptor\/provisionkeyid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"provisionKeyId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor/init(from:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/init(from:)","title":"init(from:)","kind":"symbol","url":"\/documentation\/fireblockssdk\/joinwalletdescriptor\/init(from:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol"},"doc://com.fireblocks.Fireblocks/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/objc(pl)NSObject"},"doc://com.fireblocks.Fireblocks/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s28CustomDebugStringConvertibleP"},"doc://com.fireblocks.Fireblocks/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/Se"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor/description()":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/description()","title":"description()","kind":"symbol","url":"\/documentation\/fireblockssdk\/joinwalletdescriptor\/description()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor/Identifiable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/Identifiable-Implementations","title":"Identifiable Implementations","kind":"article","url":"\/documentation\/fireblockssdk\/joinwalletdescriptor\/identifiable-implementations","role":"collectionGroup"},"doc://com.fireblocks.Fireblocks/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SH"},"doc://com.fireblocks.Fireblocks/s12IdentifiableP":{"title":"Swift.Identifiable","type":"unresolvable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s12IdentifiableP"},"doc://com.fireblocks.Fireblocks/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/s23CustomStringConvertibleP"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor/algorithm":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/algorithm","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"algorithm","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13FireblocksSDK9AlgorithmO","text":"Algorithm","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/fireblockssdk\/joinwalletdescriptor\/algorithm","abstract":[],"title":"algorithm"},"doc://com.fireblocks.Fireblocks/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.fireblocks.Fireblocks\/SE"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/JoinWalletDescriptor/requestId":{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/JoinWalletDescriptor\/requestId","kind":"symbol","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/fireblockssdk\/joinwalletdescriptor\/requestid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"requestId"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"JoinWalletDescriptor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JoinWalletDescriptor","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"JoinWalletDescriptor","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.fireblocks.Fireblocks\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JoinWalletDescriptor","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/title","value":"JoinWalletDescriptor"},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/fragments","value":[{"text":"JoinWalletDescriptor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1JoinWalletDescriptor\/navigatorTitle","value":[{"text":"JoinWalletDescriptor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}