{"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery"]]},"metadata":{"externalID":"s:13FireblocksSDK11KeyRecoveryC9algorithmAA9AlgorithmOSgvp","roleHeading":"Instance Property","symbolKind":"property","title":"algorithm","modules":[{"name":"FireblocksSDK"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"algorithm","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13FireblocksSDK9AlgorithmO","text":"Algorithm","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"algorithm","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Algorithm","preciseIdentifier":"s:13FireblocksSDK9AlgorithmO","text":"Algorithm","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/keyrecovery\/algorithm"]}],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/algorithm","interfaceLanguage":"swift"},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/Algorithm":{"navigatorTitle":[{"text":"Algorithm","kind":"identifier"}],"title":"Algorithm","abstract":[{"text":"Supported Signature algorithms for MPC keys","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/algorithm","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/Algorithm","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Algorithm"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery/algorithm":{"title":"algorithm","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/keyrecovery\/algorithm","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/algorithm","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"algorithm","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13FireblocksSDK9AlgorithmO","text":"Algorithm","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery":{"navigatorTitle":[{"text":"KeyRecovery","kind":"identifier"}],"title":"KeyRecovery","abstract":[{"type":"text","text":"Information about the recover MPC keys containing key id String, Algorithm and KeyRecoveryStatus for each key"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/keyrecovery","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyRecovery","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"KeyRecovery","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/title"},{"op":"replace","value":[{"text":"KeyRecovery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/fragments"},{"op":"replace","value":[{"text":"KeyRecovery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/navigatorTitle"}]}]}