{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery"]]},"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/keyId","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"FireblocksSDK"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"externalID":"s:13FireblocksSDK11KeyRecoveryC5keyIdSSSgvp","title":"keyId"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/keyrecovery\/keyid"]}],"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery":{"navigatorTitle":[{"text":"KeyRecovery","kind":"identifier"}],"title":"KeyRecovery","abstract":[{"type":"text","text":"Information about the recover MPC keys containing key id String, Algorithm and KeyRecoveryStatus for each key"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/keyrecovery","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyRecovery","kind":"identifier"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery/keyId":{"title":"keyId","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/keyrecovery\/keyid","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/keyId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/title","value":"KeyRecovery"},{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/fragments","op":"replace","value":[{"kind":"identifier","text":"KeyRecovery"}]},{"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"KeyRecovery"}]}]}]}