{"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksEvent"]]},"metadata":{"externalID":"s:13FireblocksSDK0A5EventO6BackupyAcA03KeyD0C_AA0A5ErrorVSgtcACmF","title":"FireblocksEvent.Backup(_:_:)","roleHeading":"Case","modules":[{"name":"FireblocksSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Backup"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyBackup","text":"KeyBackup"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:13FireblocksSDK0A5ErrorV","text":"FireblocksError"},{"kind":"text","text":"?)"}],"role":"symbol","symbolKind":"case"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Backup"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyBackup","kind":"typeIdentifier","text":"KeyBackup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13FireblocksSDK0A5ErrorV","text":"FireblocksError","kind":"typeIdentifier","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksError"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/fireblocksevent\/backup(_:_:)"]}],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksEvent\/Backup(_:_:)","interfaceLanguage":"swift"},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksEvent/Backup(_:_:)":{"identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksEvent\/Backup(_:_:)","kind":"symbol","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/fireblockssdk\/fireblocksevent\/backup(_:_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Backup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"KeyBackup","kind":"typeIdentifier","preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyBackup"},{"text":", ","kind":"text"},{"text":"FireblocksError","kind":"typeIdentifier","preciseIdentifier":"s:13FireblocksSDK0A5ErrorV"},{"text":"?)","kind":"text"}],"title":"FireblocksEvent.Backup(_:_:)"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksError":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FireblocksError"}],"url":"\/documentation\/fireblockssdk\/fireblockserror","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FireblocksError"}],"title":"FireblocksError"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksEvent":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FireblocksEvent"}],"url":"\/documentation\/fireblockssdk\/fireblocksevent","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FireblocksEvent"}],"title":"FireblocksEvent"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyBackup":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyBackup","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyBackup","kind":"identifier"}],"url":"\/documentation\/fireblockssdk\/keybackup","abstract":[{"type":"text","text":"Information about the generated MPC keys containing key id String, Algorithm and KeyBackupStatus for each key"}],"navigatorTitle":[{"text":"KeyBackup","kind":"identifier"}],"title":"KeyBackup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/title","value":"KeyBackup"},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/fragments","value":[{"text":"KeyBackup","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyBackup\/navigatorTitle","value":[{"text":"KeyBackup","kind":"identifier"}]}]}]}