{"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksEvent"]]},"metadata":{"externalID":"s:13FireblocksSDK0A5EventO7RecoveryAcA11KeyRecoveryCSg_AA0A5ErrorVSgtcACmF","roleHeading":"Case","symbolKind":"case","title":"FireblocksEvent.Recover(_:_:)","modules":[{"name":"FireblocksSDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Recover","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyRecovery","text":"KeyRecovery","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:13FireblocksSDK0A5ErrorV","text":"FireblocksError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Recover","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyRecovery","text":"KeyRecovery","kind":"typeIdentifier","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13FireblocksSDK0A5ErrorV","text":"FireblocksError","kind":"typeIdentifier","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksError"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/fireblocksevent\/recover(_:_:)"]}],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksEvent\/Recover(_:_:)","interfaceLanguage":"swift"},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksEvent/Recover(_:_:)":{"title":"FireblocksEvent.Recover(_:_:)","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/fireblocksevent\/recover(_:_:)","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksEvent\/Recover(_:_:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Recover"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@FireblocksSDK@objc(cs)KeyRecovery","text":"KeyRecovery","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:13FireblocksSDK0A5ErrorV","text":"FireblocksError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery":{"navigatorTitle":[{"text":"KeyRecovery","kind":"identifier"}],"title":"KeyRecovery","abstract":[{"type":"text","text":"Information about the recover MPC keys containing key id String, Algorithm and KeyRecoveryStatus for each key"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/keyrecovery","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyRecovery","kind":"identifier"}]},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksError":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FireblocksError"}],"url":"\/documentation\/fireblockssdk\/fireblockserror","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FireblocksError"}],"title":"FireblocksError"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/FireblocksEvent":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/FireblocksEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FireblocksEvent"}],"url":"\/documentation\/fireblockssdk\/fireblocksevent","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"FireblocksEvent"}],"title":"FireblocksEvent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"KeyRecovery","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/title"},{"op":"replace","value":[{"text":"KeyRecovery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/fragments"},{"op":"replace","value":[{"text":"KeyRecovery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/navigatorTitle"}]}]}