{"hierarchy":{"paths":[["doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery"]]},"metadata":{"externalID":"s:13FireblocksSDK11KeyRecoveryC4fromACs7Decoder_p_tKcfc","roleHeading":"Initializer","symbolKind":"init","title":"init(from:)","modules":[{"name":"FireblocksSDK"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"decoder","kind":"internalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"Decodable.init(from:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/fireblockssdk\/keyrecovery\/init(from:)"]}],"identifier":{"url":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/init(from:)","interfaceLanguage":"swift"},"references":{"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK":{"role":"collection","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK","url":"\/documentation\/fireblockssdk","title":"FireblocksSDK"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery/init(from:)":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery\/init(from:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/fireblockssdk\/keyrecovery\/init(from:)","abstract":[],"title":"init(from:)"},"doc://com.fireblocks.Fireblocks/documentation/FireblocksSDK/KeyRecovery":{"navigatorTitle":[{"text":"KeyRecovery","kind":"identifier"}],"title":"KeyRecovery","abstract":[{"type":"text","text":"Information about the recover MPC keys containing key id String, Algorithm and KeyRecoveryStatus for each key"}],"role":"symbol","kind":"symbol","url":"\/documentation\/fireblockssdk\/keyrecovery","type":"topic","identifier":"doc:\/\/com.fireblocks.Fireblocks\/documentation\/FireblocksSDK\/KeyRecovery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyRecovery","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"KeyRecovery","path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/title"},{"op":"replace","value":[{"text":"KeyRecovery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/fragments"},{"op":"replace","value":[{"text":"KeyRecovery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.fireblocks.Fireblocks~1documentation~1FireblocksSDK~1KeyRecovery\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}